### ISSUE TITLE
Invalid JSON issue

### ISSUE THREAD

**Issue by hdneo** [dracula/gamemaker-studio#14]
The new GameMaker versions popsup with invalid json issue in the theme (the older version works fine).

The issue is quite simple to fix - the keys under ColorPalette needs double qoutes.

So a valid default_theme.json should look like this:

`{
    "SkinName": "Dracula",
    "VersionTag": "0",
    "ColourPalette": {
        "ins_font_range_invalid_text_bg": "#21222c",
        "ins_header": "#21222c",
        "ins_listbox_multisel_stripe": "#21222c",
        "ins_object_eventlist_stripe": "#21222c",
        "ins_path_table_bg": "#21222c",
        "ins_path_table_stripe": "#21222c",
        "ins_separator_dark_1": "#21222c",
        "ins_separator_dark_2": "#21222c",
        "ins_sticky_panel": "#21222c",
        "ins_table_header": "#21222c",
        "ins_table_stripe": "#21222c",
        "listview_bg": "#21222c",
        "listview_item_mouseover": "#21222c",
        "listview_item_selection": "#21222c",
        "listview_label": "#21222c",
        "listview_panel_bar": "#21222c",
        "listview_panel_bg": "#21222c",
        "assetbrowser_treeview_folder": "#21222c",
        "smartguide_ruler_bg": "#44475a"
    }
}`

As i was unable to create a PR - could you please fix this ?

**Comment by tonystr** [comment]
Thank you for reporting this issue! I've committed a change now that makes the keys quoted
